# Generated by Django 4.2.5 on 2023-09-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesApp', '0002_create_initial_account_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttier',
            name='thumbnail_sizes',
            field=models.JSONField(),
        ),
    ]
